[workspace]
resolver = "3"
members = [
    "forc-wallet"
]

[workspace.package]
edition = "2024"
authors = ["Fuel Labs <contact@fuel.sh>"]
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/forc"